apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-for-docker-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
     labels:
        app: test
    spec:
      containers:
      - name: hello-world
        image: docker.io/vibhavanand/go-for-docker:latest
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 90
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 60
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
